language: node_js
node_js: 
  - "node"
  - "8"
sudo: enabled
services: 
  - docker
before_install: 
  - docker build -t totoroeric/docker-react -f Dockerfile.dev .
script: 
  - docker run totoroeric/docker-react npm run test -- --coverage

